@startuml main
class 用户 {
    用户名
    邮箱
    密码hash
}
class 书评 {
    创建时间
    内容
}
class 书评评 {
    创建时间
    内容
}
class 组 {
    创建时间
    组名
    简介
}
class 书单 {
    创建时间
    书单名
    简介
}

用户 - 书评: 创建 >
用户 - 书评评: 创建 >

书评 -down- 书目录: 评价范围 >
书评 -left- 书单: 属于 >
书评 -up- 书评评: 评价 <
书评评 - 书评评: 评价 > 
书目录 -left- 书籍: 属于 >
用户  -left-  组: 属于 > 
用户  -left-  组: 创建 > 
用户 -down- 书单: 创建 > 
用户 - 书单: 增删 > 

书单 "1..n" -down- "1" 组: 属于 > 

书单 -down- 书籍: 包含 > 

@enduml