@startuml main

用户 -right-> (添加书籍到书库)
用户 -left-> (删除书库书籍)
用户 -up-> (加入组)
用户 -up-> (登录)
用户 -up-> (创建组)

用户 <-down- 组员
组员 -left-> (退出组)
组员 -down-> (添加书评)
组员 -down-> (添加书评评)
组员 -left-> (应答投票)

组员 <-right- 管理者
管理者 -right-> (发起投票)
管理者 -down-> (修改书单)

(发起投票) -up-> (发起增删书投票)
(发起投票) -right-> (发起放逐投票)

@enduml